[package]
name = "illegal_SW_Developer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.43", features = ["derive"] }
dhcproto = "0.13.0"
hex = "0.4.3"
mac_address = "1.1.8"
pcap = "2.3.0"
rand = "0.9.2"
utf8-decode = "1.0.1"
